<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5A74DQH" failures="1" tests="5" name="Test" time="21.506" errors="0" timestamp="2023-01-27T12:56:07 PST">
  <testcase classname="naveenAutomation.Tests.MyAccountTest" name="verifyAlertBannerForInvalidLoginCredentials" time="1.282"/>
  <testcase classname="naveenAutomation.Tests.MyAccountTest" name="verifyLogin" time="0.042">
    <skipped/>
  </testcase> <!-- verifyLogin -->
  <testcase classname="naveenAutomation.Tests.MyAccountTest" name="verifyLogin" time="0.049">
    <skipped/>
  </testcase> <!-- verifyLogin -->
  <testcase classname="naveenAutomation.Tests.MyAccountTest" name="verifyLogin" time="0.048">
    <failure type="java.lang.AssertionError" message="Login Failed expected [My Account1] but found [My Account]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [My Account1] but found [My Account]
at naveenAutomation.Tests.MyAccountTest.verifyLogin(MyAccountTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="naveenAutomation.Tests.AccountLoginTest" name="verifyAlertBannerForInvalidLoginCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- verifyAlertBannerForInvalidLoginCredentials -->
</testsuite> <!-- Test -->
